language: python

# use container infra for linux
sudo: false

python:
  - 3.5
  - 3.4
  - 3.3
  - 3.2
  - 2.7
  - 2.6
  - pypy
  - pypy3
install:
  - pip install pyflakes pylint
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# install: "sudo apt-get install"
# command to run tests, e.g. python setup.py test
script:
  - python cpplint_unittest.py
  - pyflakes cpplint.py
  - pyflakes cpplint_unittest.py
  - python cpplint.py --help
  - if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then pylint --max-locals=25 --max-line-length=100 --max-attributes=10 -d bad-indentation,invalid-name,too-many-statements,multiple-statements,global-statement,missing-docstring,too-many-branches,too-many-return-statements,too-many-arguments,fixme,bad-continuation,bad-option-value,redefined-builtin,too-few-public-methods,no-self-use,too-many-lines,too-many-function-args,unused-argument,anomalous-unicode-escape-in-string,too-many-boolean-expressions   cpplint.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then pylint --max-locals=25 --max-line-length=120 --max-attributes=10 --max-public-methods=200 -d bad-indentation,invalid-name,too-many-statements,multiple-statements,global-statement,missing-docstring,too-many-branches,too-many-return-statements,too-many-arguments,fixme,bad-continuation,bad-option-value,redefined-builtin,too-few-public-methods,no-self-use,too-many-lines,too-many-function-args,unused-argument,protected-access,unused-variable,global-at-module-level,anomalous-unicode-escape-in-string   cpplint_unittest.py; fi